global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - products-service:4001
          - upload-service:4002
          - mail-service:4003

  - job_name: storefront
    static_configs:
      - targets: [nginx-exporter:9113]

  - job_name: service-health
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://products-service:4001/health
          - http://upload-service:4002/health
          - http://mail-service:4003/health
          - http://web:3000/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
